name: Build and Push Server Docker Image

on:
  push:
    paths:
      - 'src/server/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Extract current version
        id: extract-version
        run: |
          echo "VERSION=$(cat .version-server)" >> $GITHUB_ENV

      - name: Increment version number
        id: increment-version
        run: |
          VERSION=$(echo $VERSION | awk '{print $1 + 0.01}')
          echo "VERSION=$VERSION" > .version-server
          echo "::set-output name=VERSION::$VERSION"

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/server:${{ steps.increment-version.outputs.VERSION }} -f src/server/Dockerfile .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/server:${{ steps.increment-version.outputs.VERSION }}

      - name: Update docker-compose version
        run: |
          sed -i "s|image: ${{ secrets.DOCKER_HUB_USERNAME }}/server:.*|image: ${{ secrets.DOCKER_HUB_USERNAME }}/server:${{ steps.increment-version.outputs.VERSION }}|g" docker-compose.yml

      - name: Commit docker-compose version update
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add docker-compose.yml .version-server
          git commit -m "Update server image version to ${{ steps.increment-version.outputs.VERSION }}"
          git push
